### ISSUE TITLE
No zk payment scheduled after C-c on mainnet

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yajsapi#127]
mf | macOS BigSur | yajsapi 0.3.0-alpha.7 | No zk payment scheduled after C-c

[yajsapi-blender-term.log](https://github.com/golemfactory/yajsapi/files/5971905/yajsapi-blender-term.log)
[yagna_rCURRENT (3).log](https://github.com/golemfactory/yajsapi/files/5971902/yagna_rCURRENT.3.log)

same on js Windows
ederenn, Win 10 yajsapi 0.3.0-alpha.7

[yagna_rCURRENT.log](https://github.com/golemfactory/yajsapi/files/5971910/yagna_rCURRENT.log)
[yajsapi-current.log](https://github.com/golemfactory/yajsapi/files/5971911/yajsapi-current.log)
[yajsapi.log](https://github.com/golemfactory/yajsapi/files/5971912/yajsapi.log)

**Comment by filipgolem** [comment]
Commit fdcad356 should fix this issue.

**Comment by maaktweluit** [comment]
please note windows kills subtree of processes differently then posix..

could be this can never be fully fixed

**Comment by filipgolem** [comment]
> please note windows kills subtree of processes differently then posix..
> 
> could be this can never be fully fixed

Payments after ctrl+c mentioned in this issue are fixed (commit fdcad35). Ctrl+c causes cancellation token to be cancelled - which stops everything gracefully in `yajsapi` - no processes are abruptly ended, this is not OS-dependent.

The only problem is that `node` returns to the terminal (i.e. you can issue commands, at least on macOS) when Ctrl+C is pressed - even though the signal handler is present and everything is shutting down correctly.

**Comment by mateuszsrebrny** [comment]
Ok, so I undertand won't fix :)
