### ISSUE TITLE
zksync rounds transactions amounts but yajsapi doesn't

### ISSUE THREAD

**Issue by ederenn** [golemfactory/yajsapi#130]
nieznanysprawiciel - ubuntu js 

```2021-02-16 12:46:03 [yajsapi] info: Finished waiting for payments. Summary:
┌─────────┬──────────────┬────────────────────┬────────────────┬─────────────────────┐
│ (index) │  Agreement   │   Provider Name    │ Tasks Computed │        Cost         │
├─────────┼──────────────┼────────────────────┼────────────────┼─────────────────────┤
│    0    │ '63d536dcff' │ 'grotesque-spring' │       4        │ 0.07113841256833334 │
│    1    │ '14e60901a7' │  'bristlecone.4'   │       1        │   0.037414834267    │
│    2    │ '9bf4364dea' │    'jiuzhang.4'    │       1        │   0.034413148302    │
└─────────┴──────────────┴────────────────────┴────────────────┴─────────────────────┘
2021-02-16 12:46:03 [yajsapi] info: Total Cost: 0.14296639513733334
```

**Comment by filipgolem** [comment]
> nieznanysprawiciel - ubuntu js
> 
> ```
> ┌─────────┬──────────────┬────────────────────┬────────────────┬─────────────────────┐
> │ (index) │  Agreement   │   Provider Name    │ Tasks Computed │        Cost         │
> ├─────────┼──────────────┼────────────────────┼────────────────┼─────────────────────┤
> │    0    │ '63d536dcff' │ 'grotesque-spring' │       4        │ 0.07113841256833334 │
> │    1    │ '14e60901a7' │  'bristlecone.4'   │       1        │   0.037414834267    │
> │    2    │ '9bf4364dea' │    'jiuzhang.4'    │       1        │   0.034413148302    │
> └─────────┴──────────────┴────────────────────┴────────────────┴─────────────────────┘
> 2021-02-16 12:46:03 [yajsapi] info: Total Cost: 0.14296639513733334
> ```

What is the expected behaviour?

**Comment by mateuszsrebrny** [comment]
Expert opinion from @Wiezzel @pnowosie says - it would be reaaly hard to present numbers in *apis exactly the way zkSync books (at zkscan.io)

Closing as "Won't fix"
