### ISSUE TITLE
JS test strategy (is mdt test implementation OK? what we want to do with test in JS?)

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yajsapi#141]

**Comment by mateuszsrebrny** [comment]
- we pull it in, run on GH actions, only when it works we make the check required
   - there is the timeout seemingly worrying
- goth is not ready to effortlessly run `yajsapi` tasks just now
- next step (after adding ava to CI) 
   - add test as we go
   - potentially later - add tests to more interesting places
- goth tests of yajsapi are also good idea

**Comment by shadeofblue** [comment]
is this valid anymore?
