### ISSUE TITLE
Make provider summary count periodic

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/yajsapi#190]
I'm referring to this log line: `[yajsapi] info: Received proposals from 444 providers so far`. Currently it's logged for every new proposal received, including times when a task is already confusing.

Since our networks have grown these lines are now spamming the `INFO` output making it less readable. I suggest we either print this periodically (every n seconds) or move the message to `DEBUG` level.

**Comment by filipgolem** [comment]
Fixed: https://github.com/golemfactory/yajsapi/pull/230
