### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by mySoul8012** [golemfactory/yajsapi#305]
![image](https://user-images.githubusercontent.com/34295098/170831590-fd32413b-80cf-489c-8b57-faf7e956b673.png)

**Comment by shadeofblue** [comment]
@mySoul8012 please ensure that you have followed the handbook introduction. Specifically, please ensure these steps:

1. https://handbook.golem.network/requestor-tutorials/flash-tutorial-of-requestor-development#generate-the-app-key

2. `set YAGNA_APPKEY=your-32-char-app-key` -> as described in https://handbook.golem.network/requestor-tutorials/flash-tutorial-of-requestor-development/run-first-task-on-golem

reopen only if it still fails after you your yagna app key added to the environment
