### ISSUE TITLE
investigate backward compatibility of ya-ts-client

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yajsapi#37]
ya-ts-client versioning

**Comment by mdtanrikulu** [comment]
https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

> Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4
> 
> Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows > patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions > 0.0.X.

For us "patch updates for versions 0.X >=0.1.0" rule applies. Means it's safe to use caret range for the ya-ts-client version.
i.e. If we update ya-ts-client from 0.1.x to 0.2.0, the previous yajsapi versions will keep using the 0.1.x version of ya-ts-client.

But if we want full control over minor changes for the future we can switch to the tilde `~` range versioning at anytime before v1.0.0.
