### ISSUE TITLE
Replace Bluebird library

### ISSUE THREAD

**Issue by mgordel** [golemfactory/yajsapi#377]

**Comment by Braunmann** [comment]
There is no simple "plug&play" solution to replace bluebird. It is require to refactor `yajsapi/utils/eventLoop.ts` and usage across all of the loops in code. 


moreover, currently in the code we can meet specific methods for bluebird, such as `isPending()` which is not exists on native promises. Usage:
 - [yajsapi/executor/agreements_pool.ts:177](https://github.com/golemfactory/yajsapi/blob/master/yajsapi/executor/agreements_pool.ts#L177)
 - [yajsapi/executor/index.ts:841](https://github.com/golemfactory/yajsapi/blob/master/yajsapi/executor/index.ts#L841)
 - [yajsapi/executor/index.ts:842](https://github.com/golemfactory/yajsapi/blob/master/yajsapi/executor/index.ts#L842)
 - [yajsapi/executor/index.ts:845](https://github.com/golemfactory/yajsapi/blob/master/yajsapi/executor/index.ts#L845)

probably need a refactor method `start_worker` too [yajsapi/executor/index.ts:693](https://github.com/golemfactory/yajsapi/blob/master/yajsapi/executor/index.ts#L693)

**Comment by mgordel** [comment]
To be done in #396
