### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Braunmann** [golemfactory/yajsapi#440]

**Comment by VanDavv** [comment]
A couple of the ones I've been involved in:

https://github.com/luxonis/depthai-python
https://github.com/luxonis/depthai
https://github.com/luxonis/depthai-experiments
https://github.com/luxonis/depthai-experiments/tree/master/gen2-yolo

A couple of the ones that are available on the internet:
https://github.com/ai/size-limit#readme
https://github.com/aimeos/aimeos-typo3#readme
https://github.com/ajeetdsouza/zoxide#readme

Or this beauty - https://github.com/dec0dOS/amazing-github-template#readme

Overall structure
```
Title
(optional) badges
One-liner about what is in the repo
(optional) Demo video/GIF
Installation
  - start with most common
  - move on to more complex (e.g. using Docker or building from source)
Usage
Other content (usually features description or integration guides)
Links to support
```
