### ISSUE TITLE
Windows bug fixes

### ISSUE THREAD

**Issue by mgordel** [golemfactory/yajsapi#467]
- [x] file path resolver
- [x] task timeout handling
- [ ] CORS does not work on some windows system
- [x] yacat example does not work, check "'"
- [x] explore if pino.js can be used as logger (max 2h investment)
- [x] websocat - add info it will not work in windows

**Comment by VanDavv** [comment]
- Add mention to add `yagna` directory to Windows PATH

Windows > System > Advanced > Environment Variables > Path

- Add better handling for JS when the binary is not found
