### ISSUE TITLE
[UX] Add user friendly warning for new added apis

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/yajsapi#47]
If anyone tries to run updated yapapi/yajsapi from source (or on upcoming release when released) with yagna < 0.5.0, they will have 404 status code for new payment api.

What I propose instead, it's better to indicate "to be able to use this version of sdk you need to update yagna to something above >= 0.5.0" warning, so user will know what needs to be done.

**Comment by mgordel** [comment]
This is already obsolete for the current version
