### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by mgordel** [golemfactory/yajsapi#478]
Adding configuration options to the PinoLogger so that can save logs to a file in the appropriate form (csv, json??)

**Comment by pgrzy-golem** [comment]
Solution: Use factory functions to initialize loggers, leave default to console logging.

- [ ] Create null logger factory in utils module (to be able to disable the logging completely) 
- [ ] Create a console logger factory in utils module (used by default if no logger is provided)
- [ ] Create a file logger that will write logs to file
- [ ] Create unit tests
