### ISSUE TITLE
Registry integration

### ISSUE THREAD

**Issue by pociej** [golemfactory/yajsapi#504]
make yajsapi working with tags from https://registry.dev.golem.network/

to avoid breaking existing examples we should  distinguish tags  from hashes

**Comment by jalas167** [comment]
@pociej we need info how to check if the hash is valid, or or how dsitinguish  tags from hashes

**Comment by pociej** [comment]
@jalas167 fortunately tags and hashes are  easy to distinguish due to fact tags are of the pattern `[author]/[repository]:[tag]` so simple [regex](https://github.com/golemfactory/yajsapi/blob/504-registry-integration/yajsapi/package/package.ts#L52) is enough. Also it keeps backward compatibility, you can call both `TaskExecutor.create('somesuperlonghash2313123')`  as well as `TaskExecutor.create('jalas167/blender:latest')`.

**Comment by mgordel** [comment]
Done in https://github.com/golemfactory/yajsapi/pull/505
