### ISSUE TITLE
"undefined offers have been collected from the market"

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yajsapi#53]
the warning message lacks the actual value and uses a value of `undefined` instead

2020-11-17 17:40:04 [yajsapi] warn: undefined offers have been collected from the market, but
             no provider has responded for 20s. Make sure you're using the latest released versions of yagna and yajsapi, and the correct subnet.

**Comment by mdtanrikulu** [comment]
it was a simple missing about number checking, added to my own pr, will ship with it.
